github: [metadata]

url: "https://cienciadedadosuff.github.io"

title: Ciência de dados - UFF

email: your-email@example.com
description:

twitter_username: CienciaDeDadosUFF
github_username:  CienciaDeDadosUFF

permalink: /cursos/notebooks/:categories/:title:output_ext

sass:
  sass_dir: assets/css
  
plugins:
  - jekyll-feed
  - jekyll-regex-replace
  - jekyll-github-metadata
